---
name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
author: iamenr0s

inputs:
  namespace:
    description: The [Docker Hub](https://hub.docker.com/) namespace where the image can be found. Defaults to `robertdebock`.
    required: false
    default: iamenr0s
  image:
    description: The image you want to run on. Defaults to `rockylinux9`.
    required: false
    default: rockylinux9
  tag:
    description: The tag of the container image to use. Defaults to `latest`.
    required: false
    default: latest
  options:
    description: Options you can pass to [`tox`](https://tox.readthedocs.io/en/latest/), for example `--parallel all`.
    required: false
  command:
    description: What command to pass to [molecule](https://molecule.readthedocs.io/en/latest/), for example `create` or `syntax`. Defaults to `test`.
    required: false
    default: test
  scenario:
    description: The molecule scenario to run. Default to `default`.
    required: false
    default: default

runs:
  using: docker
  image: 'docker://iamenr0s/github-action-molecule:latest'
  env:
    ANSIBLE_ROLES_PATH: "../"
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    namespace: ${{ inputs.namespace }}
    image: ${{ inputs.image }}
    tag: ${{ inputs.tag }}
    options: ${{ inputs.options }}
    command: ${{ inputs.command }}
    scenario: ${{ inputs.scenario }}

branding:
  icon: play
  color: green
